# -*- coding: utf-8 -*-
"""Copy of Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w_84todZ33EP4TJdjC6IXbm_9y91NqjI
"""



"""GAME DATA

# New Section
"""

import pandas as pd
import matplotlib.pyplot as plt #untuk visualisasi data sesudah dan sebelum
import seaborn as sns

# Baca file CSV
file_path = "steam-200k.csv"  # Pastikan file sudah ada di lokasi yang benar
df = pd.read_csv(file_path)

# Tampilkan beberapa baris pertama
print(df.head())
# Pertama yang harus di lakukan ada drop duplicate nya dulu / tidak di remove secara permanen
df_cleaned=df.drop_duplicates()
# lalu remove file chachenya
df_cleaned.to_csv ("steam-200k.csv", index=False)
print(df.duplicated().sum())

# Visualisasi distribusi kolom 'Game'
plt.figure(figsize=(12,6))
sns.histplot(df_cleaned['Game'], bins=50, kde=False, color='green')
plt.title('Distribusi Game')
plt.show()

#save file yang udah di bersihkan
from google.colab import files
files.download("steam-200k.csv")

"""DATA PHK PERUSAHAAN"""

import pandas as pd

file_path = "layoff.csv"  # Pastikan file sudah ada di lokasi yang benar
df = pd.read_csv(file_path)
print (df.head(10))

Avg_income_per_company = df_cleaned.groubly ""



# HAPUS DULU
df_cleaned = df.dropna() # FILE BARU DROP BELUM DI BERSIHKAN SEHINGGA BELUM BERJALAN
cleaned_file_path = "layoff.csv"
df_cleaned.to_csv(cleaned_file_path, index=False) # Harus di remove permanen jika ingin di tampilkan

#VISUALISASI DATA KE BENTUK TABEL
rows_after = df_cleaned.shape[0]
print (f"jumlah setelah pembersihan",rows_after)
print (f"file bersih: {cleaned_file_path}")
print (df_cleaned.head(100))

mean_income=df_cleaned["funds_raised_millions"].mean()
print("rata-rata pendapatan perusahaan", mean_income)
avg_income_per_company = df_cleaned.groupby("company")["funds_raised_millions"].mean().sort_values(ascending=False)

import matplotlib.pyplot as plt
import seaborn as sns
avg_income_per_company = df_cleaned.groupby("company")["funds_raised_millions"].mean().sort_values(ascending=False)
top_companies= avg_income_per_company.head(10)
plt.figure(figsize=(8, 5))
sns.barplot(x=top_companies.values, y=top_companies.index, palette="viridis")
plt.xticks(rotation=90)
plt.xlabel("perusahaan", fontsize=12)
plt.ylabel("pendapatan rata-rata", fontsize=12)
plt.title("rata-rata pendapatan perusahaan", fontsize=14)
plt.grid(axis="y",linestyle="--", alpha=0.7)

plt.show()

import matplotlib.pyplot as plt
import seaborn as sns
avg_layoff_per_company = df_cleaned.groupby("company")["total_laid_off"].mean().sort_values(ascending=False)
top_companies= avg_layoff_per_company.head(10)
plt.figure(figsize=(8, 4))
sns.barplot(x=top_companies.values, y=top_companies.index, palette="viridis")
plt.xticks(rotation=90)
plt.xlabel("perusahaan", fontsize=12)
plt.ylabel("layoff rata-rata", fontsize=12)
plt.title("rata-rata layoff perusahaan", fontsize=14)
plt.grid(axis="y",linestyle="--", alpha=0.7)

plt.show()